// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wytfvikwukngfrcfdjnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dGZ2aWt3dWtuZ2ZyY2Zkam5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzQ5NjMsImV4cCI6MjA1ODMxMDk2M30.ncSNRaxOXVBx3pGVRUHMkyNVpC31Q8J7XuHqHwsKt-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});